fix Base.eltype methods and functions that take Type parameters
apache/arrow-julia pull request #404
Opened 2023-03-14 00:16 UTC by baumgold

2023-05-26 20:02 UTC, quinnj commented on src/ArrowTypes/src/ArrowTypes.jl
> +isstringtype(::Type{T}) where {stringtype, T<:ListKind{stringtype}} = stringtype
This seems like a more complicated equivalent?

2023-05-26 20:05 UTC, quinnj requested changes
Was the original issue that we were defining `eltype` on the _instances_ instead of types? That makes sense to me and I agree we should fix. But all the changes like:
```julia
isstringtype(::Type{T}) where {stringtype, T<:ListKind{stringtype}} = stringtype
```
should be reverted, as they're just over-complicating the methods and are functionally equivalent. i.e. in this particular example, `ListKind` is already concrete, so `T <: ListKind` doesn't really match any _additional_ types, so we're just introducing an unnecessary type parameter in `T`.

2023-06-02 04:08 UTC, baumgold commented
I reverted the changes you suggested as I can't seem to remember why I suggested them in the first place.

2023-06-02 17:12 UTC, quinnj approved these changes

2023-06-02 17:12 UTC, merged